name: Build and Deploy Prouduction Dashboard

on:
  release:
    types:
      - published

jobs:
  build:
    uses: "./.github/workflows/deployment_workflow.yml"
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    with:
      environment: production
      image_name: gcr.io/nexus-link/nexus-link-web-production
      service_name: nexus-link-web-production
