name: "Deployment workflow"

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: string
      docker_image:
        description: "Docker Image"
        required: true
        type: string
      service_name:
        description: "GCP Service Name"
        required: true
        type: string

    secrets:
      GCP_SA_KEY:
        description: "GCP Service Account Key"
        required: true
      PROJECT_ID:
        description: "GCP Project ID"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-app-b2c-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-app-b2c-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-


      - if: ${{ steps.cache-app-b2c-client-admin-npm.outputs.cache-hit != 'true' }}
        name: List node modules
        continue-on-error: true
        run: npm list

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Install dependencies and build app
        run: |
          export NODE_OPTIONS="--max_old_space_size=6096"
          npm install
          npm i @nrwl/nx-linux-x64-gnu
          npm i @esbuild/linux-x64
          npm run build

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.docker_image }} -f .
          gcloud auth configure-docker
          docker push ${{ inputs.docker_image }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ inputs.service_name }}
          project_id: ${{ secrets.PROJECT_ID }}
          image: ${{ inputs.docker_image }}

      - name: Use output
        run: echo "The URL is ${{ steps.deploy.outputs.url }}"